name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 9 * * 1-5' # Run at 9 AM, Monday through Friday

env:
  # Global environment variables
  CI: true
  FORCE_COLOR: 1

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false # Continue running other browsers even if one fails
      matrix:
        # Run tests on multiple browsers
        browser: [chromium, firefox, webkit]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps ${{ matrix.browser }}
    
    - name: Run Playwright tests
      run: npx playwright test Flnal.spec.ts --project=${{ matrix.browser }} --reporter=html,json,junit
      env:
        # Add any environment variables your tests need here
        BROWSER: ${{ matrix.browser }}
    
    - name: Upload Playwright HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.browser }}
        path: playwright-report/
        retention-days: 30
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.browser }}
        path: test-results/
        retention-days: 30
    
    - name: Upload Screenshots (on failure)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: screenshots-${{ matrix.browser }}
        path: test-results/
        retention-days: 7

  # Alternative single browser job (disable matrix above and enable this)
  test-single:
    if: false # Set to true if you want to use this instead of the matrix strategy
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: npx playwright test FInal.spec.ts --reporter=html,json
    
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30

  # Optional: Notification job
  notify:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Notify on success
      if: needs.test.result == 'success'
      run: echo "✅ All Playwright tests passed!"
    
    - name: Notify on failure
      if: needs.test.result == 'failure'
      run: echo "❌ Some Playwright tests failed. Check the artifacts for details."
